### ISSUE TITLE
Have a plan for the transition from UBI9/8 images to C9S for ODH and RHEL for RHODS

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#105]
Due to a lot of missing packages on UBI-based images, it requires moving to CentOS Stream 9 base images on the upstream repo, and RHEL for the downstream. 

Things to consider (so far): 

- This differentiation in the base image between the two repositories may lead to use two different repositories. Let's think about how we may avoid double maintenance. (Maybe by using submodules)
- On downstream, we need to be registered on the subscription manager

**Comment by harshad16** [comment]
Thanks for the possible solution for making the change.
Seems like a doable solution.


We should also evaluate the implication of making a change from centos and rhel
would like to cause any kinda concern downstream as well.

**Comment by harshad16** [comment]
Necessary image are split between UBI/Centos/RHEL.
Closing this issue as the requirements are fulfilled.
