### ISSUE TITLE
Update to Python 3.11

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/notebooks#122]
There are finally an official Python 3.11 image available upstream:

https://catalog.redhat.com/software/containers/ubi8/python-311/
https://catalog.redhat.com/software/containers/ubi9/python-311

It would be great to get the notebook images updated to Python 3.11.

**Comment by guimou** [comment]
Many packages are not supported yet unfortunately: https://pyreadiness.org/3.11/

**Comment by strangiato** [comment]
Thanks for sharing that @guimou.

As of right now pyreadiness is reporting 56% green and 43% white (which means the packages don't explicitly say they support 3.11, not that it doesn't work).  By comparison 3.9 reports 78% green.

It looks like a lot of packages just simply don't report a readiness status in pypi unfortunately.

Of the packages listed in the pipfile in the "datascience" notebook here:

https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/Pipfile

All of the packages that are part of the "top 360" packages tracked on pyreadiness are reporting as green.  Obviously there are a lot of packages that aren't part of the "top 360" and dependencies as well that we need to consider in addition to other packages in other notebook "flavors".

With that being said, are there any specific packages that you are concerned about that aren't reporting as supported in 3.11 yet or is there a specific threshold for pyreadiness that we would need to reach before making 3.11 available as an option?  What is driving the decision to making 3.11 available?

A major driver for me pushing for 3.11 is that 3.9 is over half way through its support cycle.  From the RH perspective the 3.8 container went EOL about a year before the end of the python support cycle.  If the plan for 3.9 is similar that leaves us will only about a year of support left on the 3.9 container (I can't find any official documentation on the planned Python container image support cycle so assuming we are going to do something similar for 3.9).  So we are asking customers to start development on their projects in something that potentially has only a year of support available.  The DS dev cycle additionally has cascading issues where a model developed in one python/package version might have tight coupling with the python/package version being used to serve the model.  This means that we are asking customers to not only develop in a nearing EOL python version, but also potentially release production applications in a nearing EOL python version.

On top of that, there are a huge number of very desirable features in 3.11, including major performance improvements, better error messaging, faster startup times, and [more](https://realpython.com/python311-new-features/).

I also feel that this is something we should be pushing and validating early on the ODH side so that by the time we are ready to make this available in RHODS it has been well tested in ODH.  Even if it is a non-default version of the notebooks it seems better to start finding where the issues are now so we can start tracking the readiness for RHODS, or even better yet, reporting and working the issues upstream.

Just a side thought, I would love to see the creation of some support standards and lifecycle management as an ADR to help formalize how we handle updates to python (and other languages) in a predictable way for our customers.

**Comment by guimou** [comment]
OK, let me put some meat around the bones.
First thing to mention is that I am as impatient as you are to switch to 3.11, mainly for the performance gains. So I've been monitoring the status of many projects/libraries for the most part of 2023. Up til about May this was still problematic with some important libs.
Now things seem to be better, but there are still some issues. Not directly due libraries compatibility, but what I still see now and then is "There is a bug with library x at the latest version. Until it's corrected, downgrade to this version to have your code working". However, this previous version may not be 3.11-compatible... So depending on what you do it can be a hit or miss.
So all of this to say that I have only recently begun to look at updating the contrib repo with a 3.11 branch. I'm in the process of setting up a new release of those contrib workbenches, so I will see what works or not with this branch.
Regarding the process for ODH or RHODS this is something else. I guess there should be new discussions shortly with what we want to do for upcoming releases. Part of this discussion is the point I brought getting away from UBI images in favor of CentOS Stream/RHEL, as UBI lack too many base OS packages when you need to do more advanced things. This is the path I'm taking with contrib images, I don't know if have an official decision for ODH/RHODS.

**Comment by harshad16** [comment]
Moving this to JIRA: https://issues.redhat.com/browse/RHOAIENG-4533
Thanks all for the discussion. 
Please refer to the JIRA for further development.
