### ISSUE TITLE
Can Elyra DS pipelines work at all in Disconnected Environments?

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#127]
Description of problem:

Possible/practical to use DS pipelines in disconnected environments? 

I'm looking at some of the tasks (generated by Elyra) and there is a bunch of "curl this file from github" and "pip install some more things". 

JIRA: https://issues.redhat.com/browse/RHODS-9427

**Comment by shalberd** [comment]
It doesn't look like it yet.

Related issue at Elyra: https://github.com/elyra-ai/elyra/issues/2805

**Comment by harshad16** [comment]
This issue wasn't worked in sprint 1.31
moving it to sprint 1.32

**Comment by atheo89** [comment]
The pull request has been submitted and can be found [here](https://github.com/opendatahub-io/notebooks/pull/166). To properly evaluate the changes, it's important to set up a disconnected environment. This will allow us to test the modifications in isolation thoroughly.

**Comment by harshad16** [comment]
As mentioned the real issue is happening during pipeline runtime, which runs on runtime images.
https://elyra.readthedocs.io/en/latest/recipes/running-elyra-in-air-gapped-environment.html#runtime-environment-dependencies
As elyra installs the bootstrapper.py and requirements.txt by downloading with curl on runtime
To fix the issue of outside call, we would have get the files in the runtime images itself.

we track 4 runtime images currently:
`datascience`, `pytorch`, `tensorflow` and base `ubi9-python3.9`
 https://github.com/opendatahub-io/notebooks/tree/main/jupyter/datascience/ubi9-python-3.9/runtime-images
as the first 3 are created by us, including the files in them, can be done from the Dockerfile.

for [ubi9-python3.9 runtime](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/runtime-images/ubi9-py39.json) , we need to create additional `minimal` folder in runtime to track them.
- [ ] Create additional `minimal` runtime
- [ ] Configure ocp-ci to build the runtime-minimal image.
- [ ] swap the runtime-image image in place ubi9-python3.9 image in runtime-images.


 Additionally, with the swap of new files, we include the env vars to reference the internal files rather than the external files to get this fixed. 
```
 # Environment vars set for accessing following dependencies for air-gapped enviroment
export ELYRA_BOOTSTRAP_SCRIPT_URL="file:///opt/app-root/bin/utils/bootstrapper.py"
export ELYRA_PIP_CONFIG_URL="file:///opt/app-root/bin/utils/pip.conf"
export ELYRA_REQUIREMENTS_URL="file:///opt/app-root/bin/utils/requirements-elyra.txt"
```

**Comment by jbyrne-redhat** [comment]
@harshad16 Does this release note text sound OK?

### Running pipelines from Elyra within JupyterLab not supported in a disconnected environment

Previously, you could not run a data science pipeline from Elyra (within JupyterLab) in a disconnected environment. This issue is now resolved.

**Comment by harshad16** [comment]
@jbyrne-redhat , let's wait for the QA approval on this. 
Seems like @mwaykole found some issue with the fix. 
in discussions on this. Will keep you posted.

**Comment by shalberd** [comment]
Thank you for all your work on this, alleviating the inadequacies or false assumptions of Elyra.

**Comment by harshad16** [comment]
Based on the finding from @mwaykole. 
Even though the requirement.txt and additional files are now being picked from local. 
```
Downloading file:///opt/app-root/bin/utils/bootstrapper.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 31480  100 31480    0     0  30.0M      0 --:--:-- --:--:-- --:--:-- 30.0M
Downloading file:///opt/app-root/bin/utils/requirements-elyra.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1462  100  1462    0     0  1427k      0 --:--:-- --:--:-- --:--:-- 1427k
Requirement already satisfied: packaging in /opt/app-root/lib/python3.9/site-packages (23.1)
```

still the installation of packages mentioned in the requirements.txt
would try to connect with PyPI, which is external. 
we need to allow users to introduce there own pip.conf , so users can setup proxy PyPI and use that.

ReOpening this issue in place of https://github.com/opendatahub-io/notebooks/issues/202

**Comment by harshad16** [comment]
Further details: 
- Completed in Sprint 1.32, failed QA. 
ReOpened.

**Comment by harshad16** [comment]
Closing this as the part of this was achieved
and remaining bit will be completed with this: https://github.com/opendatahub-io/notebooks/issues/202
