### ISSUE TITLE
Add piplock-renewal GH action on 2023b branch

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#134]
Since we are moving on updates for the 2023b we need also there the same procedures that the 2023a branch is following. 

- [ ] Create the `piplock-renewal-2023b.yml`  check how you can do it [here](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/piplock-renewal-2023a.yml)

**Comment by harshad16** [comment]
Note: This action seems to be broker:
https://github.com/opendatahub-io/notebooks/actions/runs/6462211841
lets work on investigating and fixing it.

**Comment by harshad16** [comment]
With the action running : https://github.com/opendatahub-io/notebooks/actions/workflows/piplock-renewal-2023b.yml
we can close this issue.
Thanks for the work.
