### ISSUE TITLE
Configure the 2023b branch on openshift CI 

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#135]
**Acceptance criteria**

- [ ] Configure the 2023b branch on openshift CI. example [here](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml#L411)
- [ ] Create the command in Makefile to accommodate the changes needed in openshift-ci. example [here](https://github.com/opendatahub-io/notebooks/blob/0e6c7bec8529b73247a8e36a1d98428442ff76fe/Makefile#L265)  
- [ ] Instructions to build and mirror the new images. example [here](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023a.yaml)

**Comment by harshad16** [comment]
This issue seems to have been completed. 
https://github.com/openshift/release/pull/42784
Thanks for the work :100:
