### ISSUE TITLE
Placeholder in DSP runtime configuration prepends unnecessary data

### ISSUE THREAD

**Issue by dimakis** [opendatahub-io/notebooks#141]
Whilst configuring DSP runtime configuration I got stung by this, the placeholder prepends a `:port/pipeline` to the route url (it also says service as opposed to route --just a nit pick).
It doesn't work with it, but works without it.
![image](https://github.com/opendatahub-io/notebooks/assets/28638411/31c6344c-2ff8-45b4-85ca-f4e6b1797a07)

JIRA: https://issues.redhat.com/browse/RHOAIENG-363

**Comment by harshad16** [comment]
Only for notebook-devs:


Goal: Figure out service work in the endpoint URL , if not change the placeholder to route-url.

**Acceptance criteria**

- [ ] Test if this issue is actually happening 
- [ ] Setup a cluster with RHODS/ODH, create any of the notebook with elyra. 
- [ ] Setup the runtime-configuration with service:port URL, Test the pipeline.
- [ ] Change the placeholder, if the service:port URL doesn't work.

**Comment by harshad16** [comment]
Based on the discussion with community contributors.
The users would like to have the option to use service-url if it possible.
https://odh-io.slack.com/archives/C035J0KA6UB/p1689970211014419?thread_ts=1689965765.550419&cid=C035J0KA6UB
https://odh-io.slack.com/archives/C035J0KA6UB/p1690179701867089?thread_ts=1689965765.550419&cid=C035J0KA6UB

as per this comment, it would be worth investigating 
- Enhancement to the current flow to enable users to use service-URL. 


As this require some more investigation,
Moving this to next sprint 1.32.

**Comment by harshad16** [comment]
Based on the work, 
Pipeline can be used from service directly , by using the port 

Example: `https://ds-pipeline-pipelines-definition.test.svc.cluster.local:8888`

**Comment by chtyler** [comment]
@harshad16  

Can you please confirm the documentation requirement for this. Would you like to add this to release notes as a known issue? 

Would you recommend updating the existing user-facing documentation to further clarify this fix?

**Comment by harshad16** [comment]
@chtyler, It is not an issue.
More documentation updates.
we need to update the documentation, stating that, the user can use the service-based URL.
instead of the route-based one.
Let's find a better way of updating this in the documentation.

**Comment by chtyler** [comment]
@harshad16 

I have created the following Jira to cover this work: https://issues.redhat.com/browse/RHODS-12954

**Comment by harshad16** [comment]
This work is now completed with effort.
Service can be used with port info, as now the network policies are set in place.
Closing this issue. Thanks.
