### ISSUE TITLE
Update recommended accelerators for ootb imagestreams

### ISSUE THREAD

**Issue by Gkrumbach07** [opendatahub-io/notebooks#151]
The dashboard UI will soon start supporting all types of accelerators, not just Nvidia GPUs, as a result, imagestreams need to be updated to include an annotation to define recommended accelerators_. The UI will parse the JSON blob, but will expect an array of strings. Those strings should be the accelerator identifier.

_Note: the annotation is not required for non accelerator recommended images i.e. you dont need to include an empty array_

An example annotation of the format the UI expects is: 

```yaml
opendatahub.io/recommended-accelerators: '["nvidia.com/gpu", "habana.com/gen1"]'
```

**Acceptance criteria**
- [ ] update each OOTB image stream with using the above annotation with compatible accelerator identifiers
- [ ] update the documentation of [imagestream](https://github.com/opendatahub-io/notebooks/blob/main/docs/workbench-imagestreams.md) with the annotation details.

**Comment by harshad16** [comment]
Any image in directory [odh-manifests/notebooks](https://github.com/opendatahub-io/odh-manifests/tree/master/notebook-images) with CUDA included in this notebook-software description, for example: [here ](https://github.com/opendatahub-io/odh-manifests/blob/59d87c23f987f80c94d1ceadbf47679616e1b080/notebook-images/base/jupyter-pytorch-notebook-imagestream.yaml#L18)
needs to be included with annotation `opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'`  under metadata -> annotation, for example [here](https://github.com/opendatahub-io/odh-manifests/blob/59d87c23f987f80c94d1ceadbf47679616e1b080/notebook-images/base/jupyter-minimal-gpu-notebook-imagestream.yaml#L10)
