### ISSUE TITLE
Pipfile.lock file Should not exist in the container root directory

### ISSUE THREAD

**Issue by orangeji11** [opendatahub-io/notebooks#152]
I noticed that pipfile.lock is copied to the [root directory /.](https://github.com/red-hat-data-services/notebooks/blob/38d2bc5f10327666df04d599469061c99b09732c/base/ubi8-python-3.8/Dockerfile#L19C21-L19C21), and when the pip dependency is installed, the [./Pipfile.lock file](https://github.com/red-hat-data-services/notebooks/blob/38d2bc5f10327666df04d599469061c99b09732c/base/ubi8-python-3.8/Dockerfile#L21C89-L21C89) under the working directory /opt/app-root/bin is deleted, and I can also see the pipfile.lock file in the container root directory.is this a problem please?
![image](https://github.com/opendatahub-io/notebooks/assets/39036074/ad2eadae-8236-4c37-be6c-a037c987b5de)

**Comment by harshad16** [comment]
yes it shouldn't be on the root.
Great catch.

Thanks for fix and contribution :100:

**Comment by harshad16** [comment]
Closing this issue, as it is fixed in the PR.
