### ISSUE TITLE
Enhancing Support for Older OOTB Images: Retention and Deprecation Flagging

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#154]
Depends: https://github.com/opendatahub-io/notebooks/issues/236

As part of the better support for older OOTB images issue (https://github.com/opendatahub-io/notebooks/issues/131), we should consider keeping when we move to drop the current N-1, to keep this resource around and flag it so the dashboard to be able to read and ignore it when rendering. 

This can be accomplished by introducing an [annotation ](https://github.com/opendatahub-io/odh-manifests/blob/master/notebook-images/base/jupyter-minimal-notebook-imagestream.yaml#L30)flag on the tag assigned to the resource we are deprecating. Examples of such annotation flags could be:

-  `image-deleted:true` or `deprecated-image:true ` 
-  `deprecation-text: This notebook is no longer supported; please upgrade to a newer version`

**Acceptance criteria**
- [x] Include the annotation to the deprecated version of the imagestream.
   - Annotation to be used is: `opendatahub.io/image-tag-outdated:true`: https://github.com/opendatahub-io/notebooks/pull/315
- [x] Sync with ODH-dashboard workflow to use this annotation.: https://github.com/opendatahub-io/odh-dashboard/issues/2084

**Comment by chtyler** [comment]
The Jira for the user-facing documentation work is here: https://issues.redhat.com/browse/RHODS-12817

**Comment by harshad16** [comment]
Both the work is complete , both from notebooks and dashboard side
Closing this as complete.
