### ISSUE TITLE
We may want to remove the "Test" Runtime in the Elyra notebooks

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#156]
**Description of problem:**

I can see 2 pipeline runtimes in Elyra:
![image-2023-06-22-12-41-07-533](https://github.com/opendatahub-io/notebooks/assets/14028058/91f8cc1f-1b6b-41b8-916f-8fb0f75ad258)

But then, when I submit: 
![image-2023-06-22-12-42-40-835](https://github.com/opendatahub-io/notebooks/assets/14028058/30e3d987-1e62-4589-bc12-7cacda76a85c)

I can see both. 

and picking the wrong one simply blows up:
![image-2023-06-22-12-43-19-465](https://github.com/opendatahub-io/notebooks/assets/14028058/aa0d711e-ebf6-4847-97c0-c530a56434aa)

**Prerequisites** (if any, like setup, operators/versions):
Steps to Reproduce
<steps>
Actual results:
Expected results:
Reproducibility (Always/Intermittent/Only Once):
Build Details:
Workaround:
Additional info:

JIRA: https://issues.redhat.com/browse/RHODS-9456

**Comment by harshad16** [comment]
Increasing the priority based on the conversation here:
https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1691542182974989

**Comment by erwangranger** [comment]
just came across this again today in a different way. 
Was using a project in which I had not deployed any pipeline server. 
And yet, there is a "run as pipeline" button in Elyra, and the only pipeline config is "test" 
<img width="1024" alt="image" src="https://github.com/opendatahub-io/notebooks/assets/32554862/c3e829ec-578a-4aab-9671-8540f3996f20">

and of course, it fails if you try to run it: 
<img width="900" alt="image" src="https://github.com/opendatahub-io/notebooks/assets/32554862/cd26859f-49a1-4415-b9bf-aad9be8412e7">

**Comment by harshad16** [comment]
Thanks you @erwangranger  for providing more information 
we have already started the work on this. 
The PR is ready: #165 
this would definitely be included in the 1.32 release.

**Comment by jbyrne-redhat** [comment]
@harshad16 Does this release note text sound OK?

### Elyra included an example runtime called Test

Previously, Elyra included an example runtime configuration called `Test`. If you selected this configuration when running a data science pipeline, you could see errors. The `Test` configuration has now been removed.

**Comment by harshad16** [comment]
@jbyrne-redhat , How about this: 

Workbenches with  Elyra included an example runtime called Test

Previously, the workbenches/Notebooks had included an example Elyra runtime configuration called `Test`. 
If this configuration was selected, it wouldn't have executed instead would have thrown errors, as it was just for example.
In an effort to reduce the confusion, the `Test` configuration has been now removed.
