### ISSUE TITLE
Create test notebooks for Minimal & Standard data science notebooks

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#180]
The test_notebook.ipynb file should evaluate the Python packages and the versions that are included on. 

In this document described in detail the test framework -> https://docs.google.com/document/d/1sctOblkWdpUrv1DzzrzK_nzMMtA44awKmCvXDVAkVXo/edit

**Comment by harshad16** [comment]
This is completed.
Marking this as completed. 
Thanks
