### ISSUE TITLE
Create test notebooks for TrustyAI notebook

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#182]
The test_notebook.ipynb file should evaluate the Python packages and the versions that are included on.

In this document described in detail the test framework -> https://docs.google.com/document/d/1sctOblkWdpUrv1DzzrzK_nzMMtA44awKmCvXDVAkVXo/edit

**Comment by harshad16** [comment]
This is now completed with #244
Thanks for all the work.
