### ISSUE TITLE
state manifests for importing notebooks image in repo

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#185]
Currently, users can only rely on the odh-manifests to deploy notebook images. 
As that is the only place where the manifests are kept. 

**Plan of action/ Acceptance criteria**
- [x] Keep a copy of notebook manifests on the notebook repo.
- [x] Plan to update notebook images with the image sha digest update.
- [x] Plan to update the digest in release branches. 

Reference: https://github.com/opendatahub-io/opendatahub-operator/issues/424#issuecomment-1670799870

**Comment by zdtsw** [comment]
think we can close this issue?

**Comment by harshad16** [comment]
marking this as closed.
:+1:
