### ISSUE TITLE
Explore the package version to be updated

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#191]
Explore the package version to be updated.

Acceptance Criteria:

- [x] Update with the latest and compatible packages the **Future Release (N) v2023b** column in this file: [OOTB Notebook Image Releases n&n-1 ](https://docs.google.com/spreadsheets/d/1LaTLTQSY9g8Rgau6jJwBQmZjd2NBfnElYZthfb9Bhwk/edit#gid=0)

**Comment by atheo89** [comment]
The [OOTB Notebook Image Releases n&n-1](https://docs.google.com/spreadsheets/d/1LaTLTQSY9g8Rgau6jJwBQmZjd2NBfnElYZthfb9Bhwk/edit#gid=0) spreadsheet has recently received an update. You can find the most current Python versions for each notebook under the "Future Release (N+1) v2023b" column. As we begin the process of updating the notebooks, please make sure to reference and utilize these updated versions.

**Comment by harshad16** [comment]
The package versions were described on the spreadsheet from the exploration. 
This suffices the requirement for the issue. 
Thanks :100:
