### ISSUE TITLE
Update the test notebooks for the 2023b release

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#192]
Update the test notebooks for the 2023b release

Target branch: `2023b`

Depends-On: https://github.com/opendatahub-io/notebooks/issues/178

**Acceptance criteria**
- [x] Update the test with respect to the notebook package versions. [link](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/test/test_notebook.ipynb)
- [ ]  ~Update the makefile with the commands.~
- [ ]  ~Update the GH workflow/Ocp CI.~

Reference: https://github.com/opendatahub-io/notebooks/issues/178

**Comment by dibryant** [comment]
All of the notebook test look good and up to date with the correct package versions. Updating the make file a pull request will be opened for that.

**Comment by dibryant** [comment]
Makefile was updated and looks good!

**Comment by dibryant** [comment]
> > All of the notebook test look good and up to date with the correct package versions. Updating the make file a pull request will be opened for that.
> 
> Hey Diamond, could you kindly perform a thorough review of the package versions currently present in our test notebooks on the main branch? I've noticed that after syncing from the 2023b to the main branch, there have been some changes.
> 
> For instance, I've observed that the minimal (ubi8 & 9) definitely requires an update. It currently specifies jupyter_version 3.5 ([link](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/minimal/ubi9-python-3.9/test/test_notebook.ipynb)), but we have actually transitioned to version 3.6. You can find the details in the [pipfile](https://github.com/opendatahub-io/notebooks/blob/main/jupyter/minimal/ubi9-python-3.9/Pipfile). Accordingly for the rest.

Will look into this must've just changed thank you!

**Comment by harshad16** [comment]
Thanks for working on this.
Marking this as complete.
Closing the issue.
