### ISSUE TITLE
Addition of CodeFlare SDK to datascience base image

### ISSUE THREAD

**Issue by dimakis** [opendatahub-io/notebooks#197]
The codeflare project [SDK ](https://pypi.org/project/codeflare-sdk/) lives here. It would be a great addition to the data science notebook and its subsidiaries. 

**Goal**:
- Install the codeflare SDK  in data science and rest.

**Acceptance criteria**
- [x] Install the package in the Notebook image requirements.
- [ ] #295
- [x] Include this in the release notes.

**Comment by harshad16** [comment]
As this is targetted for the tech preview of 1.34 , targeting this for that sprint. 
cc: @dimakis  @anishasthana

**Comment by anishasthana** [comment]
Sounds good! Thanks @harshad16

**Comment by harshad16** [comment]
Documentation to be included:
- https://github.com/opendatahub-io/distributed-workloads/blob/main/Quick-Start.md
- https://github.com/project-codeflare/codeflare-sdk/tree/main/demo-notebooks

**Comment by harshad16** [comment]
Due this, https://github.com/opendatahub-io/notebooks/pull/196#issuecomment-1737582282
the injection is on hold.
DW team is working on removing the pytorch-lighting requirement.
https://github.com/project-codeflare/codeflare-sdk/pull/360

with the new release of codeflare , we can work on reviewing.

**Comment by harshad16** [comment]
This issue is targetted for RHODS 1.35
https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1695846349586659?thread_ts=1695830142.181839&cid=C05NXTEHLGY

**Comment by harshad16** [comment]
As the codeflare-sdk is now available in data-sceince, pytorch, tensorflow and trustyai notebooks.
Thanks everyone for working on this.
Closing this issue.

**Comment by jstourac** [comment]
Just for the reference - the codeflare-sdk addition was done in this PR #205 . The other linked here are relevant updates of the SDK.
