### ISSUE TITLE
Can Elyra DS pipelines work at all in Disconnected Environments? #127

### ISSUE THREAD

**Issue by mwaykole** [opendatahub-io/notebooks#202]
Description of problem:

Possible/practical to use DS pipelines in disconnected environments? 

I'm looking at some of the tasks (generated by Elyra) and there is a bunch of "curl this file from github" and "pip install some more things". 

JIRA: https://issues.redhat.com/browse/RHODS-9427
JIRA: https://issues.redhat.com/browse/RHODS-10967

Creating a duplicated issue of  https://github.com/opendatahub-io/notebooks/issues/127   as i am  not able to reopen and the issue was not fixed

**Comment by harshad16** [comment]
Closing this duplicate issue.

**Comment by shalberd** [comment]
@mwaykole thank you for also thinking of this, nice.

I am linking the post in the related issue that I think summarized the main remaining tricky config issue that you found out about

https://github.com/opendatahub-io/notebooks/issues/127#issuecomment-1709547310

**Comment by harshad16** [comment]
The changes mentioned in the PR.
There wont be any runtime install of python package , all the required pre-requisite packages
are preinstalled on the packages.

If a user, want to install python packages, they can use pip , and provide
their pypi index URL via PIP_INDEX_URL.

**Comment by harshad16** [comment]
Closing this issue as complete

**Comment by chtyler** [comment]
@harshad16 - Can you confirm if there is a documentation requirement for this work? Do the docs need to be updated as a result of ensuring that Elyra works with a disconnected setup?

**Comment by harshad16** [comment]
Yes @chtyler , there is a docs requirement.
We should connect over this.

**Comment by chtyler** [comment]
@harshad16 - I have created https://issues.redhat.com/browse/RHODS-12962 to cover this docs work. We can discuss this tomorrow.
