### ISSUE TITLE
Introduce pipeline version with numbers(v1,etc) instead of datastamp

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#206]
Currently when pipelines are created using elyra from the Notebooks, each additional iteration of the pipeline run, and create a new pipeline version, the pipeline version names are defined in the following manner: `<pipeline-name>+<datastamp>`.

UX feels it would be more convenient for the users to have the pipeline version names defined with numbers instead of data stamps. like `<pipeline-name>+<number>` example: `test-v1`

**Acceptance criteria**

- [ ] Extend the pipeline version name to include the number in place of the timestamp.
https://github.com/elyra-ai/elyra/blob/3c27ada25a27b719529e88268bed38d135e40805/elyra/pipeline/kfp/processor_kfp.py#L312C58-L312C70
   - There is a [GET](https://www.kubeflow.org/docs/components/pipelines/v1/reference/api/kubeflow-pipeline-api-spec/#operation--apis-v1beta1-pipeline_versions-get) call for pipeline_version, to gather the count of the pipeline_version.

- [ ] Open the PR upstream on elyra, if it taking time to merge.
Open PR to patch it in the notebook for the time being. 
https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/utils/processor_kfp.patch
https://github.com/opendatahub-io/notebooks/blob/57b82522d53b41252ecc53c8d2a7be9303ae7c2b/jupyter/datascience/ubi9-python-3.9/Dockerfile#L41C68-L41C71

**Comment by rkpattnaik780** [comment]
Raised a pull request [elyra#3183](https://github.com/elyra-ai/elyra/pull/3183).

**Comment by andrewballantyne** [comment]
@HumairAK any update on if the backend can make this happen?
