### ISSUE TITLE
RStudio and VSCode try to connect to HTTP

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#227]
In the connection flow, there is a redirect to an http session (before being sent back to https) that makes thing impossible to work on networks filtering http traffic (the first call, normally answered with a redirect, never makes it to OpenShift).
Investigate NGINX configuration.

Original Issue: https://github.com/opendatahub-io-contrib/workbench-images/issues/34
Related conv:  https://odh-io.slack.com/archives/C0330L52N22/p1694538000643369

**Comment by harshad16** [comment]
Related-to: https://github.com/opendatahub-io/opendatahub-community/issues/72

**Comment by shalberd** [comment]
solved, tested in our corporate environment. Scheme is now based on original request, so that when we start with https, it is https all the way, and when we start with http, more for dev purposes, it is http all the way.
