### ISSUE TITLE
Pytorch image: wrong/inconsistent version of CUDA

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/notebooks#23]
Pytorch comes with its own embedded version of CUDA. The version of Pytorch used in this image, 1.8.1, comes with CUDA 10.4.

Whatever other version of CUDA you embed in the container is not used and does not matter. So even if the CUDA used in this images is 11.4.2 (herited from base CUDA), Pytorch will only use 10.4.

This has two drawbacks:
- It can lead to misinterpretation and errors in reproducibility (see screenshot where different tools report different things), especially as the NVidia Operator injects its own version of CUDA and tools in the container! We see here three different version: nvidia-smi reports 11.7 (comes from the operator), nvcc reports 11.4 (comes from the image build), pytorch reports 10.4 (comes from embedded CUDA):
![image](https://user-images.githubusercontent.com/3944034/203642737-5c48891c-937f-4ff5-9e94-61adbe38f9d3.png)

- You end up with a bigger container image than necessary because you have two version of CUDA deployed, one never being used.

Possible solutions:
- Start with a standard base image without CUDA, as anyway Pytorch won't use it. Drawback: if other supplemental tools want to use CUDA, they may or may not find the one coming with CUDA.
- Compile Pytorch from source instead if intstalling it from PyPI (or Conda, same issue), using the CUDA installation already present in the base image. Drawback: much more work.

**Comment by atheo89** [comment]
Thank you @guimou for opening this issue. We have updated the PyTorch notebook, you may find the new image using the following tag: `quay.io/opendatahub/notebooks:jupyter-pytorch-ubi8-python-3.8-a4b003a` . It is included on the **v1.3.0** release.
