### ISSUE TITLE
Documentation for the updates of 2023b.

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#234]
**Acceptance criteria**
- [x] Update the documentation for 2023b workbench, in docs and wiki. 
- [x] Release Notes on deprecation of the old version and inclusion of 2023b images.
- [ ] Update a scope of 2023b. ex: [link](https://docs.google.com/document/d/1WBEYkB9UDPjiEM7pmtreXf8YWIWL_TAixthEf3ywUyA/edit)

**Comment by atheo89** [comment]
Release notes are covered on this issue: https://github.com/opendatahub-io/notebooks/issues/273

**Comment by atheo89** [comment]
Docs update PR: https://github.com/opendatahub-io/notebooks/pull/281

**Comment by harshad16** [comment]
Thanks for working on this.
Marking this as complete.
