### ISSUE TITLE
Fix the security of the notebook containers

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#235]
Quay security scan,

Check on the fixes that can be made for notebook images to fix the security issue.
https://quay.io/repository/opendatahub/workbench-images?tab=tags

Page shows the vulnerability: https://quay.io/repository/opendatahub/workbench-images/manifest/sha256:08ca15319061594adab1663e2db15c588197d3ebb6e33eb854411102c947b3e6?tab=vulnerabilities

**Acceptance criteria**
- [x] Check what package change has increased the vulnerability and create a report.
- [x] Reduce the number of reported vulnerabilities on quay.
- [x] Make sure the update of the package and binaries don't break the images.
- [x] make a report for the vulnerabilities reduced in a google sheet or docs.

**Comment by rkpattnaik780** [comment]
I have compiled a [list](https://docs.google.com/spreadsheets/d/1fX3dIO5rmi6BorB5CwttLukpI4Enwo-APQO-vgyZ8K0/edit?usp=sharing) of vulnerabilities found by the Quay security scan in Python dependencies of the workbenches. Some immediate action items to be made:
- [ ] Upgrade tensorflow from 2.11.0 to 2.11.1 for `habana-jupyter-1.9.0-ubi8` notebook.
- [ ] Upgrade versions of grpcio and cryptography in codeflare SDK.

Cc @harshad16

**Comment by rkpattnaik780** [comment]
Reported issue in [codeflare-sdk#385](https://github.com/project-codeflare/codeflare-sdk/issues/385).

**Comment by harshad16** [comment]
Thanks for the amazing report and for making the request upstream.
Marking this as complete.
