### ISSUE TITLE
Update the digest updater workflow for 2023b on notebooks repo

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#237]
Update the [workflow](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/notebooks-digest-updater-upstream.yaml) to include 2023b changes as N version of the image.

**Acceptance criteria**
- [x] Run the digest updater with 2023b branch, check if the result correct.
- [x] Fix the digest updater to follow the 2023b pattern for `n` th image.

**Comment by atheo89** [comment]
Reopen this issue, as it should be merged with the following one in order to be completed -> https://github.com/red-hat-data-services/odh-manifests/pull/509

**Comment by harshad16** [comment]
In order to stay in line with operator team , 
we would be updating the manifests in the in-repo. 
- [ ] Update the digest-updater to update these manifests https://github.com/red-hat-data-services/notebooks/tree/main/.github/workflows

**Comment by atheo89** [comment]
Pull Requests

- In upstream: https://github.com/opendatahub-io/notebooks/pull/249
- Downstream (new operator): https://github.com/red-hat-data-services/notebooks/pull/64 
- Obsolete odh-manifests (old operator): https://github.com/red-hat-data-services/odh-manifests/pull/509

**Comment by harshad16** [comment]
The digest updater is working well and is set on appropriate locations.
Thanks for working on this. :100:
