### ISSUE TITLE
[QA] Test the habana notebooks.

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#243]
Tasks.
- [x] How to get a cluster with HPU available. 
  - [x] Explore the cluster with the QA Team.
   or 
  - [x]  Setup a cluster from https://console.redhat.com/
     Then follow this [document](https://docs.google.com/document/d/13-0FcwoZliwA0cMOU1oekdau4QT2YnlilsD-vJ_1ih4/edit).
-  [x] Implement quality assurance 
   - [x] Set the cluster with RHODS. (from jenkin with iib value for 1.34)
   - [x] Make sure the habana imagestream. 
   - [x] Spin the Habana notebook with HPU accelerator
     - [x] Follow this docs for setting accelerator profile: [Docs 1](https://docs.google.com/document/d/1wkMVnONDzMSaCnJMK_AUO0vnoHQ-oYlVmJ1b5d6tPtg/edit), [Docs 2](https://docs.google.com/document/d/1SI3FteDHIniGbx1aUW4yUk5hZVOWzbaJAsQx9BGceK8/edit#heading=h.suy8xuy3yguq)
   - [x] Test the Habana image with [tutorial](https://github.com/HabanaAI/Gaudi-tutorials/blob/main/PyTorch/quickstart_tutorial/quickstart_tutorial.ipynb)
   
Follow this issue for additional checks: https://github.com/opendatahub-io/notebooks/issues/355

**Comment by jstourac** [comment]
Optional negative testing scenarios:

* On cluster without habana the initialization should fail
* On cluster with habana operator that doesn’t match our image the initialization should fail

**Comment by jstourac** [comment]
Current status - feature has been successfuly checked with the v1.10. Based on discussion, we need to check also v1.11 - relevant operator should be available in latest 4.12.x OCP release.

Automation - TBD.

**Comment by jstourac** [comment]
One more question raised up - can the users use Habana in a maintained variant of the RHODS product? I'm not sure if I correctly distinct all difference between self-managed and managed product. In case of managed in AWS, I suppose that customer should be able to perform all necessary configuration to utilize the Habana hardware, correct? But, I am not sure that he can choose for particular location where the cluster is being provisioned :thinking_face: e.g. `us-east-1`. At the moment the Habana hardware is restricted to just `us-east-1` and `us-west-2` locations.

**Comment by jstourac** [comment]
For the record -  for release of 1.34, it was decided to go with Habana v1.10 image only, see #297.

**Comment by harshad16** [comment]
Marking this as complete , thanks for the work :100: 
Additional work would be tracker here: https://github.com/opendatahub-io/notebooks/issues/355
