### ISSUE TITLE
Display Python version on launcher

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/notebooks#25]
By default, the Python version is not displayed on the Notebook launcher, only "(ipykernel)":
![image](https://user-images.githubusercontent.com/3944034/204316329-e82ebbfb-17b4-40b9-b736-43ae4d1e045c.png)

This may become confusing when we will update images and support different versions, like version n-1 on Python 3.8 and version n on Python 3.9.
People may also want to extend images with other Python kernel versions, you must then be able to understand exactly what you are launching.

Displaying the right version would only require a small modification to the kernel specs after jupyter is installed:
`sed -i -e "s/Python.*/$(python --version)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json`
as is implemented here: https://github.com/guimou/custom-notebooks/blob/81ebdcb48121580bcec780b38e16aef4952707a4/notebook-controller-images/s2i-minimal-notebook/py39/Dockerfile#L38

Then you end up with something like this:
![image](https://user-images.githubusercontent.com/3944034/204317863-f17a1148-15d6-4653-b4d6-f83c7efd8c17.png)

**Comment by atheo89** [comment]
Close that issue. We include that change in v1.3.1 release.
