### ISSUE TITLE
Include build commit info as the annotation in the imagestream

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#252]
Currently, on the ODH dashboard, users only see the image name and image version. As some of image sha changes without the image version being updated. It would be a good approach to have build info also available for user to know something has changed on the image.

```
DataScience version 2023.1 (Build <hash>)
```

**Acceptance criteria**
- [x] Include the annotation `opendatahub.io/notebook-build-commit` with the information.
- [ ] Work with odh-dashbaord on what annotation to be picked on.

Extension:
- [ ] #354
    -  Folllow the above issue for automated extension.

QA:
- [ ] Extend the ods-ci to check for the new annotation.

Related-to: 
https://github.com/opendatahub-io/odh-dashboard/issues/1917

**Comment by chtyler** [comment]
This affects the user-facing documentation. The documentation team needs to document the new reference to the build version.

The Jira covering this work is: https://issues.redhat.com/browse/RHODS-12816
