### ISSUE TITLE
[Bug] elyra-pipeline validate CLI command fails for pipelines with parameters and default properties 

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/notebooks#257]
Describe the issue
Running elyra-pipeline validate and by extension elyra-pipeline export fails silently with pipelines that contain both pipeline parameters and default properties.

To Reproduce

Create a simple Elyra pipeline with a single node.
Add a pipeline parameter in the Pipeline Parameters configuration tab.
Open the Pipeline Properties configuration tab.
Save the pipeline, e.g. as test.pipeline.
Validate the pipeline through the CLI: elyra-pipeline validate test.pipeline.
Screenshots or log output
The following error message without details is printed after running the above validation command:

Log Output
Expected behavior
Given that pipelines with parameters and default properties are valid in general, the validation command should resolve without any errors.
In case of actual issues within the pipeline file, there should be detailed information about these issues.

Elyra version: 3.15.0
Installation source: quay.io/opendatahub/workbench-images:cuda-jupyter-tensorflow-ubi9-python-3.9
Deployment type: Red Hat OpenShift Data Science 1.33.0
Operating system: linux

Reference: 
- https://github.com/elyra-ai/elyra/issues/3190
- https://redhat-internal.slack.com/archives/C03UGJY6Z1A/p1697118084945979

**Acceptance criteria**
- [x] Run the pipeline through validate pipeline [here](https://github.com/elyra-ai/elyra/blob/650eca10337909b66f3eb842313eaeb8362bc95d/elyra/cli/pipeline_app.py#L282) to debug the validation.
- [x]  Share the solution with the team. 

QA:
- [ ] Extend ods-ci to perform the pipeline validation action.

**Comment by chtyler** [comment]
@harshad16 - Would you like this declaring in the release notes as a known issue?

**Comment by harshad16** [comment]
@chtyler , do you know what is a criteria for known issue, is all the issue we find on the workbench 
needs to be on release notes ?

**Comment by chtyler** [comment]
@harshad16 - Any issue that affects user-facing functionality is a candidate for declaration in the release notes.
