### ISSUE TITLE
consider making pipeline runtime image image_name reference sha256 digest format

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/notebooks#259]
related to

https://github.com/opendatahub-io-contrib/workbench-images/issues/44

docker image tag can be put in tags array of json.
the image_name should be in digest format 

for all runtime image jsons at `notebooks/jupyter/datascience/`

so as to be compatible with restricted network environments and ImageContentSourcePolicy. Important for restricted network environments / airgapped. Yes, users can add additional runtimes via GUI per user notebook / PVC, but the default runtimes as delived via ODH in the docker jupyter datascience images should be in the correct format as well.

image_name is used for pulling images, tags are shown in Elyra GUI, just like display_name.

i.e.
```
{
    "display_name": "CUDA Datascience with Python 3.11 (CentOS Stream 9)",
    "metadata": {
        "tags": ["cuda-runtime-datascience-c9s-py39_RELEASE_latest"],
        "display_name": "CUDA Datascience with Python 3.11 (CentOS Stream 9)",
        "image_name": "quay.io/opendatahub-contrib/workbench-images@sha256:bd565c0e8b4e71d7ae3fd556a2f874e6251d80db1c4c36bfe1d490f04df2bdb1"
    },
    "schema_name": "runtime-image"
}
```

**Comment by harshad16** [comment]
**Acceptance criteria**

- [ ] Change the from tag to sha256 format. ex: [link](https://github.com/opendatahub-io/notebooks/blob/000b6fec67095b39b5743f8433703621d6d0bbc9/jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json#L6)

**Comment by shalberd** [comment]
@harshad yes, and for readability in Elyra GUI, you can put the tag that was originally part of the docker image image_name in the tags array instead, as an element of that. https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/runtime-images/datascience-ubi9-py39.json#L4

![Bildschirmfoto 2023-10-17 um 19 01 30](https://github.com/opendatahub-io/notebooks/assets/21118431/47e8d5be-2920-4894-9686-cdc63c9cf406)

**Comment by harshad16** [comment]
This feature is completed with the PR: https://github.com/opendatahub-io/notebooks/pull/286
Marking this as complete, please check the next opendatahub release to see this in effect.
Closing the issue, thanks all for the work :100:
