### ISSUE TITLE
[Bug]: Update advertised TrustyAI version

### ISSUE THREAD

**Issue by asanzgom** [opendatahub-io/notebooks#301]
### ODH Component

ODH Dashboard

### Current Behavior

When creating a notebook server using TrustyAI, the advertised version is 0.2:

![image](https://github.com/opendatahub-io/opendatahub-community/assets/100594859/4f4316a2-a20d-42b2-9fe7-605b301c5031)

Meanwhile, the spawned image is 0.3.0:

```
(app-root) (app-root) pip list | grep trustyai
trustyai                        0.3.0
```

### Expected Behavior

The advertised TrustyAI version should match the one installed on the notebook

**Comment by harshad16** [comment]
@asanzgom Can you share a few more details please?
- Which image version was selected ? (ex: trustyai: 2023.1)
- Which version of ODH/RHODS installation is being used ?

**Comment by asanzgom** [comment]
@harshad16 for TrustyAI there is only one version you can choose: 
![image](https://github.com/opendatahub-io/notebooks/assets/100594859/a810be20-7804-4341-8641-c5d15382e5e9)

It was tested on RHODS 1.34 Cloud Service (ROSA Cluster)

**Comment by harshad16** [comment]
ack, this is a bug thanks for reporting.
we will try to work on this on our end.
As i can say, this will be fixed in the next release
as the display change as patch for 1.34 is probably little late.

**Comment by harshad16** [comment]
Fixed with the above linked PR.
Thanks and closing this issue
