### ISSUE TITLE
There is a typo in some docker image labels - `k9s` instead of `k8s`

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/notebooks#310]
Some Dockerfiles contains labels with the typo in the element - it contains `k9s` instead of `k8s`.

* `k8s` - refers to Kubernetes, https://kubernetes.io/:
   * >[Kubernetes](https://kubernetes.io/docs/concepts/overview/), also known as K8s, is an open-source system for automating deployment, scaling, and management of containerized applications.
* `k9s` - probably may refer to the https://k9scli.io/, didn't find any other reasonable results for this

This causes that there are both following labels in layered builds:

```
io.k8s.description
io.k8s.display-name
io.k9s.description
io.k9s.display-name
```

E.g. for latest `jupyter-pytorch-ubi9-python-3.9-2023a-20231106-3ad46bb`, [here](https://quay.io/repository/opendatahub/workbench-images/manifest/sha256:90884309bfd316466277e90f18e692f3babc330cd380e245e743067eefd434b8):

```
io.k8s.display-name="Jupyter pytorch notebook image for ODH notebooks"
io.k8s.description="Jupyter pytorch notebook image with base Python 3.9 builder image based on UBI9 for ODH notebooks"
io.k9s.display-name="Minimal Jupyter notebook image for ODH notebooks"
io.k9s.description="Minimal Jupyter notebook image with base Python 3.9 builder image based on UBI9 for ODH notebooks"
```
(there are more occurrences on more layers, I've put here just one example of this)

I suppose that we want these to be unified to `k8s` only.

We should fix it against `main`, `2023b` and `2023a` branches at least I think.

**Comment by harshad16** [comment]
It is mentioned as typo, can you share why it feels like typo ?
K8s refer kubernetes, can you share any docs that refers to K9s.
@jstourac

**Comment by jstourac** [comment]
Hi @harshad16, thank you - I updated the description to better express myself. Please, let me know whether more info is needed or if I simply misunderstood something :upside_down_face:

**Comment by harshad16** [comment]
Both the PR's are merged.
Thanks for the work and the issue.
Marking this as complete.
