### ISSUE TITLE
 Add some extensions without the need to go and install them all over again on vscode workbench

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#336]
**Why you need this feature:**

It would be nice to have on pre-installed extensions on vscode workbench

**Describe the solution you'd like:**

 Add some extensions without the need to go and install them all over again on vscode. Like Python/Jupyter/etc.

**Anything else you would like to add:**

There is a CLI on VS Code able to do this on a docker image. Ref [link](https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions)

JIRA: https://issues.redhat.com/browse/RHOAIENG-231

**Comment by harshad16** [comment]
This issue is completed with the PR #347 
Thank you for working on this.
