### ISSUE TITLE
pip install doesn't function well on jupyterlab extension withing vscode

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#338]
**What steps did you take and what happened:**
pip install complains, but when I do the suggestion (using %pip) it doesn't work 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenDatahub Version: latest
- Workbench: VS-Code
- Workbench Version: 2023.2
- Specific tool: (jupyterlab, rstudio, vscode, elyra-pipelines,etc)
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

![image](https://github.com/opendatahub-io/notebooks/assets/42587738/5e50025c-a00e-482b-8f3b-6eb2b49c8a45)

JIRA: https://issues.redhat.com/browse/RHOAIENG-232

**Comment by dibryant** [comment]
So I ran pip install for pandas, matplotlab and scipy. All were installed successfully (as seen in a screenshot below).  
<img width="1287" alt="Screenshot 2023-12-04 at 9 40 09 AM" src="https://github.com/opendatahub-io/notebooks/assets/135062655/18315e8d-71ca-4f00-a8f2-9aece3645bac">

**Comment by harshad16** [comment]
Thank you for working this issue.
Seems like there was typo from issue.

`!%` both are not needed, we should either use `!` for using a bash command like cli or `%`,  not both.
Closing this issue as complete, no changes to be made.
