### ISSUE TITLE
Relative path doesn't work on vscode

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#339]
**What steps did you take and what happened:**

Path on the same workspace is not working snp500_price_data_2011_to_2020.csv on the same dir of the notebook

- Doesn't work

   price_data = pd.read_csv('snp500_price_data_2011_to_2020.csv', index_col=[0])

- It works

   price_data = pd.read_csv('/opt/app-root/src/snp500_price_data_2011_to_2020.csv', index_col=[0])

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: (all, data-science, etc)
- Workbench Version: (2023.1, etc)
- Specific tool: (jupyterlab, rstudio, vscode, elyra-pipelines,etc)
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

**Comment by rkpattnaik780** [comment]
After testing this in cluster, it seems the relative path works as expected. We should be able to close this issue.

<img width="633" alt="Screenshot 2023-11-16 at 7 48 17 PM" src="https://github.com/opendatahub-io/notebooks/assets/23582438/a2d69f37-d5a9-43ee-89ab-fb0905583ca8">

**Comment by harshad16** [comment]
Thanks for re-testing this and clearing that this isn't a bug.
Marking this issue as complete.
