### ISSUE TITLE
Jupyterlab extension on vscode stuck in loading a file

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#340]
**What steps did you take and what happened:**

A user encountered an error in VS Code where it is stuck loading a file, unable to run cells, and also not able to rename the file. He has attached a recording of the issue on this [link](https://drive.google.com/file/d/13bIjy6FJCY2CZa2hKHG2P0hVdCG4veqZ/view?usp=drive_link). 

He got this error after renaming the workbench and cluster storage, before that it was working fine. Maybe this might be due to server overload, but thought sharing this.

**What did you expect to happen:**
Run the code from the cell

**Anything else you would like to add:**
Recording of the issue on this [link](https://drive.google.com/file/d/13bIjy6FJCY2CZa2hKHG2P0hVdCG4veqZ/view?usp=drive_link). 

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: (all, data-science, etc)
- Workbench Version: (2023.1, etc)
- Specific tool: (jupyterlab, rstudio, vscode, elyra-pipelines,etc)
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

JIRA: https://issues.redhat.com/browse/RHOAIENG-233

**Comment by harshad16** [comment]
Work on this continues, 
we are not able to replicate the issue on the cluster.
It seems to work on the replication time.

Based on further research: 
seems like some one faced this explicitly on : iOS 
https://github.com/coder/code-server/issues/6317

**Comment by harshad16** [comment]
Closing based on above comment.
