### ISSUE TITLE
 On VS Code it would be great to have an upload button/option for uploading local files.

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#341]
**Why you need this feature:**
it would be great to have an upload button/option for uploading local files.

**Describe the solution you'd like:**
Have a upload button

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jstourac** [comment]
Right click in the files explorer shows me an `Upload` option. Isn't it what is desired in this bug?

![Screenshot from 2023-11-15 13-41-48](https://github.com/opendatahub-io/notebooks/assets/12250881/8b5d5e4b-02ac-4537-9d80-1fe0c1068fd8)

**Comment by harshad16** [comment]
As mentioned above this option already exists.
closing this issue.
