### ISSUE TITLE
Issue while torch installation on R Studio workbench

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#343]
JIRA: https://issues.redhat.com/browse/RHOAIENG-368

**What steps did you take and what happened:**

Trying to install “torch”- package. Have no idea what the immediate fix is.. It is likely due to missing the cmake package. Would be nice to try it again after the required package in the previous comment is installed. 

```
{standard input}: Assembler messages:
{standard input}:14785460: Warning: end of file not at end of a line; newline inserted
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/usr/lib64/R/etc/Makeconf:200: RcppExports.o] Error 1
ERROR: compilation failed for package ‘torch’
* removing ‘/opt/app-root/src/Rpackages/4.2/torch

```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: (all, data-science, etc)
- Workbench Version: (2023.1, etc)
- Specific tool: RStudio
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

**Acceptance criteria**
- [ ] Execute the installation on the image, and debug the result.

**Comment by harshad16** [comment]
Closing this issue as we have the jira: https://issues.redhat.com/browse/RHOAIENG-368.
