### ISSUE TITLE
Create a github workflow to refresh the requirements 

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#35]
We need to keep the python sub-packages updated in order to provide weekly updates. 

For this work should be defined a github workflow that will keep these packages updated

**Comment by harshad16** [comment]
Keeping the requirements version updated can be done in a multiple ways:
- Using Bots: Dependabot from GitHub 
Update the package version and have the option to open PR based on [scheduled time](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleday).

- Using Github workflows.
The pattern followed in the notebooks repo.


Great choice of approach :+1: 
As in this method, we would have the option to debug the failed workflows and fix our source code if required.
