### ISSUE TITLE
Incorporate on vscode standard database clients for MySQL, PostgreSQL, MSSQL, and MongoDB

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#372]
**Why you need this feature:**
[Is your feature request related to a problem? Please describe in details]
This can be useful for the end user to have these on the workbench embedded.

**Describe the solution you'd like:**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
Is a follow up to this issue: https://github.com/opendatahub-io/notebooks/issues/345

https://issues.redhat.com/browse/RHOAIENG-140

**Comment by atheo89** [comment]
Do you think it would be more beneficial to incorporate this integration into the base ubi9 image, allowing all notebooks beneath it to inherit these advantages?
Currently, we only introduce them in the datascience notebook, and as a result, all other notebooks inherit these benefits. Given that we need to integrate them into vscode, this implies that we will be repeating the same procedure as was done for the datascience notebook (and possibly later for the RStudio notebook).

**Comment by harshad16** [comment]
Check in about these requirements: @harshad16

**Comment by harshad16** [comment]
Closing this issue in favor of the JIRA issue: https://issues.redhat.com/browse/RHOAIENG-140
