### ISSUE TITLE
Recommended image version label for workbench is showed for two versions

### ISSUE THREAD

**Issue by jstourac** [opendatahub-io/notebooks#373]
This is an upstream issue for the following downstream one https://issues.redhat.com/browse/RHODS-12870.

**What steps did you take and what happened:**
For workbench notebook images, there is a Recommended label showed for the latest version of the notebook image. 

Unfortunately, this seem to be broken during upgrade operation as this label is showed for two versions - the new 2023b and also for version 2023a, which was tagged with this label in previous release. We could see it with the upgrade from 1.33 to 2.4.

You can find more information in https://issues.redhat.com/browse/RHODS-12870

This issue is present only after the upgrade operation (1.33 to 2.3 ATM) and isn't present with the fresh installation.

Root cause of the issue is right in the relevant imagestreams definitions, as I can see following for one of the image:

```
   - name: '1.2'
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"JupyterLab","version": "3.2"}, {"name":
          "Notebook","version": "6.4"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8"}]'
        openshift.io/imported-from: quay.io/modh/odh-minimal-notebook-container
      from:
        kind: DockerImage
        name: >-
          quay.io/modh/odh-minimal-notebook-container@sha256:39068767eebdf3a127fe8857fbdaca0832cdfef69eed6ec3ff6ed1858029420f
      generation: 4
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: '2023.1'
      annotations:
        opendatahub.io/default-image: 'true'
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"JupyterLab","version": "3.5"}, {"name":
          "Notebook","version": "6.5"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
        opendatahub.io/workbench-image-recommended: 'true'
        openshift.io/imported-from: quay.io/modh/odh-minimal-notebook-container
      from:
        kind: DockerImage
        name: >-
          quay.io/modh/odh-minimal-notebook-container@sha256:54a5af13057df3445f917494a8cc12a0bed081c67204e00c9ed26daeaf9d0079
      generation: 4
      importPolicy: {}
      referencePolicy:
        type: Source
    - name: '2023.2'
      annotations:
        opendatahub.io/default-image: 'true'
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"JupyterLab","version": "3.6"}, {"name":
          "Notebook","version": "6.5"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9"}]'
        opendatahub.io/workbench-image-recommended: 'true'
        openshift.io/imported-from: quay.io/modh/odh-minimal-notebook-container
      from:
        kind: DockerImage
        name: >-
          quay.io/modh/odh-minimal-notebook-container@sha256:a942ab984181b1ea0bffec92473995bbb1488d65a4d1b64717385f49bfd0adf4
      generation: 4
      importPolicy: {}
      referencePolicy:
        type: Source
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: (all, data-science, etc)
- Workbench Version: (2023.1, etc)
- Specific tool: (jupyterlab, rstudio, vscode, elyra-pipelines,etc)
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

**Comment by harshad16** [comment]
For the extension, we would need support from the dashboard team to fix this: https://issues.redhat.com/browse/RHOAIENG-937
opened the following issue to cover the request.
with this, we should be able to move forward.

marking this one as complete as we complete the work with the above linked PR.
and further details would be taken in consideration on JIRA.
