### ISSUE TITLE
Add a notebook specific label

### ISSUE THREAD

**Issue by DharmitD** [opendatahub-io/notebooks#387]
**Why you need this feature:**

Right now, there's just one label `opendatahub.io/dashboard=true` for notebooks. Adding an explicit notebook specific static label would help us utilize the notebook component effectively.

**Describe the solution you'd like:**

For instance, we're trying to update the Data Science Pipelines' network policy to connect to the notebook pod. In this case, having an exclusive static label would be really helpful.

**Comment by harshad16** [comment]
Moved to JIRA: https://issues.redhat.com/browse/RHOAIENG-2220
closing this issue.
please check it out details there.
