### ISSUE TITLE
s3-browser does not work

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/notebooks#39]
At least in the Tensorflow image, the S3-browser extension does not work. The extensions stays blank:

![image](https://user-images.githubusercontent.com/3944034/220366976-13c8d05e-516b-4630-96d1-4593ed03c600.png)

And the browser console shows a 404 error:

![image](https://user-images.githubusercontent.com/3944034/220367159-64bace14-701b-4d56-ae32-c648de304249.png)

Maybe it's due to the older version of the extension that had to be used for compatibility with the rest of the packages, that may however not be compatible with this version of JupyterLab.

**Comment by harshad16** [comment]
Current notebook details:

Image: quay.io/opendatahub/notebooks:jupyter-datascience-ubi8-python-3.8
Package version list: 
```
jupyterlab              3.5.3
jupyterlab-s3-browser   0.10.1
```

Server extension enabled.
````
(app-root) (app-root) jupyter serverextension list
config dir: /opt/app-root/etc/jupyter
    elyra  enabled 
    - Validating...
      elyra  OK
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 1.5.1 OK
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyter_resource_usage  enabled 
    - Validating...
      jupyter_resource_usage  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.5.3 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.41.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 3.1.1 OK
    nbgitpuller  enabled 
    - Validating...
      nbgitpuller 1.1.1 OK
```

Logging details of past version:

The s3-browser extension was working in past.
Image: quay.io/opendatahub/notebooks:jupyter-datascience-ubi8-python-3.8-514c319
Package version list: 
```
jupyterlab              3.5.0
jupyterlab-s3-browser   0.12.0
```

Server extension enabled.
````
(app-root) (app-root) jupyter serverextension list
config dir: /opt/app-root/etc/jupyter
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 1.5.1 OK
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyter_resource_usage  enabled 
    - Validating...
      jupyter_resource_usage 0.6.4 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.5.0 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.40.1 OK
    jupyterlab_s3_browser  enabled 
    - Validating...
      jupyterlab_s3_browser  OK
    nbdime  enabled 
    - Validating...
      nbdime 3.1.1 OK
```

**Comment by harshad16** [comment]
The root cause of extension not showing up is due the missing part of server extension enablement.

On jupyterlab-s3-browser version < 0.11.1
Manual addition of  serverextension is needed by doing the following:
`jupyter serverextension enable --py jupyterlab_s3_browser`

with the following change, the newer version doesn't need the above changes anymore.
https://github.com/IBM/jupyterlab-s3-browser/commit/c55542f322c3a2261a469593f2528ad2c7ab0b03

**Comment by guimou** [comment]
Oh, yes, that's because we had to fall back on this old version that does
not behave in the "modern" way.
That's a shame because it will force to reintroduce this enabling code in
the docker build.
I still wonder if it would not be better to update s3-browser to match with
our current requirements. We don't want to stay forever on this old version
anyway. I'll try to have a look at what is blocking.

**Comment by atheo89** [comment]
Could be a solution to assign the  `jupyterlab==3.5.0` on the pipfile requirements in order to avoid this downgrade and all the consequential issues on the s3-browser?

**Comment by harshad16** [comment]
It is the `boto3` package upgrade which is causing this trouble with `jupyterlab-s3-browser` upgrade, i m testing few changes 
will open a pr for review soon.

**Comment by harshad16** [comment]
Tried 2 methods:
1st Method. Explanation: `boto3` version is to pinned: `1.24.59`
as it corresponds to `botocore` version which is compatible with latest `jupyterlab-s3-browser`.
Cons: `boto3` current version is `1.26.90` which is 2 major update higher than what we would need to pin it down to.
Commit: https://github.com/harshad16/odh-notebooks/commit/6625de1f7353d7bad5c7d251d86b721535167983

2nd Method. Explanation: Embedded enabling `jupyterlab-s3-browser` on build-time.
Commit: https://github.com/harshad16/odh-notebooks/commit/7905fb50bf3a5cad294098aaa0f2fc20f623af95

personally, I feel, we should use method 2nd, as it would enable `jupyterlab-s3-browser` and doesn't need any downgrade to a package like `boto3` which is used by data scientists in there workload as well.

Please let me know which one, we should prefer, happy to open the PR.
@guimou @atheo89

**Comment by atheo89** [comment]
Great investigation @harshad16! I agree with your point about the second method.

Furthermore, I would like to add some observations here that I had on your branch: 
-  On PyTorch Dockerfile you don't need to enable the package `jupyterlab-s3-browser` there because it is inherited by the parent image.
- The same for TensorFlow
- Just enable it only inside the DataScience Dockerfile 

Could you also include the change on the TensorFlow package https://github.com/opendatahub-io/notebooks/issues/42  ?

**Comment by guimou** [comment]
Yeah, good work @harshad16 , the second method is definitely the way to go, pinning boto3 will have tons of side effects. boto3 is updated daily, and I know I had troubles with other packages when I tried to play too much with it (mainly because of jl-s3browser).
For a quickfix that will do, until we can/have time to properly update upstream package as discussed.
