### ISSUE TITLE
Drop .z stream from Python version in JL main menu

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/notebooks#49]
After #25 , new images display the full python version when launching into the JupyterLab main menu.
For consistency with the Dashboard spawner page, I would suggest dropping the .z stream from the version string.

@guimou I understand you requested this to enable users to deal with multiple kernel versions, do you think it would be likely for users to use multiple kernel versions with the same minor but different patch?

Perhaps it would be possible to only show the .z stream when two kernels with the same minor versions are detected?

**Comment by guimou** [comment]
The configuration had two goals:
- Remove the "(ipykernel)" mention that does not bring anything apart from
confusing people.
- Indicate the Python version, not for multiple kernels (you're right, it
won't happen much), but as a reminder of which image they launched. With
n-1 and n support, they may have in their RHODS environment 3.8 and 3.9
images, then 3.9 and 3.10...

Regarding the z version it's not really important, so it can be removed for
sure. It's a slight modification to make on the Dockerfile.

**Comment by harshad16** [comment]
How to test code in local system:

1. Make the changes in the notebook and build it with following code:
`podman build -t runtime . --build-arg BASE_IMAGE=[quay.io/opendatahub/workbench-images:jupyter-minimal-ubi9-python-3.9-2023a-20230605](http://quay.io/opendatahub/workbench-images:jupyter-minimal-ubi9-python-3.9-2023a-20230605)`
2. Run the code to test:
`podman run -p 8888:8888 localhost/runtime`
3. Make sure the python version z stream is not showing.

**Comment by harshad16** [comment]
PR Under review
Moved this to next sprint 1.31.
