### ISSUE TITLE
Implement ghcr.io expiration for images and cache layers

### ISSUE THREAD

**Issue by jiridanek** [opendatahub-io/notebooks#568]
It appears that ghcr.io does not support setting expiration. The only way is to periodically delete old images. This is probably a good thing to do, just to avoid excessive storage usage.

Although there does not seem to be any limit for us, it seems to be a good practice to clean up after ourselves.

* https://github.com/WoozyMasta/quay-expiration
* https://github.com/eumel8/expire-action
* https://github.com/snok/container-retention-policy/blob/main/main.py

**Comment by caponetto** [comment]
One more option: https://github.com/marketplace/actions/ghcr-pruning

**Comment by jiridanek** [comment]
@caponetto do you have a favorite? I'm unfamiliar with the options, so I'm inclined to pick yours
