### ISSUE TITLE
Python 3.8 UBI 8 Base Image - End of Life

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/notebooks#62]
The upstream [Python 3.8 UBI 8](https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a) image that is the base of the current released notebook images is EOL in May 2023.

This repo contains dockerfiles for 3.9 based images and it appears they are published on quay but they don't appear in the official "releases" list.  They also are not currently available in odh-manifests.

It would be great to get all of the notebook images updated to Python 3.9 before the current base image goes EOL.

**Comment by harshad16** [comment]
The UBI9-based images are included in ODH release v1.5.0.
The notebook-image manifests on ODH-manifests are already updated with the new inclusion. For example:
https://github.com/opendatahub-io/odh-manifests/blob/56fd28c76543f8e322ce54ff10b34fd6eb8290ec/notebook-images/base/jupyter-datascience-notebook-imagestream.yaml#L17
https://github.com/opendatahub-io/odh-manifests/tree/v1.5.0/notebook-images/base

**Comment by zdtsw** [comment]
Should the code referring  to `ubi8-pytohn-3.8` be cleaned up along with CI jobs?
e.g today I am building https://github.com/opendatahub-io/notebooks/blob/main/base/ubi8-python-3.8/Dockerfile
got error `Error: copying system image from manifest list: Source image rejected: A signature was required, but no signature exists`

**Comment by harshad16** [comment]
We would continue to have the code for ubi8, 
till our customer has fully transitioned to the new version.
Thanks for the question.
Feel free to add more questions.
