### ISSUE TITLE
Missing libraries or OS packages to consider for next release

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/notebooks#72]
This issue is meant to catch the different libraries or OS packages that people think are missing and should be added to the standard images.
Please add your item(s) directly in comments, with a small justification/advocacy of why it should be added.

**Comment by guimou** [comment]
**libodbc**
When using pyodbc to connect to a database, libodbc.so.2 is not found on the system.
As pyodbc is a pretty standard library, it should work without having to create a custom image to include it.

**Comment by guimou** [comment]
**libsnd**
This library is needed to read/write sound files. As data analysis, model training,... can also be done on such sources (using torchaudio for example), this library should be included in the base image.

**Comment by guimou** [comment]
**drivers for current databases**
Examples: mongodb, postgres (13,14,15), mssql server (2019, 2022)

**Comment by atheo89** [comment]
The [OOTB Notebook Image Releases n&n-1](https://docs.google.com/spreadsheets/d/1LaTLTQSY9g8Rgau6jJwBQmZjd2NBfnElYZthfb9Bhwk/edit#gid=0) spreadsheet has recently received an update. You can find the most current Python versions as well as the new Python package inclusions for each notebook under the "Future Release (N+1) v2023b" column. As we begin the process of updating the notebooks, please make sure to reference and utilize these updated versions.

**Comment by dimakis** [comment]
The [CodeFlare SDK](https://pypi.org/project/codeflare-sdk)

This is used to interact with the Distributed Workloads stack.

**Comment by guimou** [comment]
@dimakis Would the CLI be useful too, or just wasted space?

**Comment by harshad16** [comment]
Completed with #205
thanks for the work.

cuda-toolkit cant be included in the UBI/RHEL images. 
Wait for this action.

**Comment by harshad16** [comment]
Closing this as complete. 
For any of the missing one, a new issue can be opened.
Thanks for working on this.
