### ISSUE TITLE
rendering Rmd Markup to pdf not working

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/notebooks#794]
**What steps did you take and what happened:**
- Took a most recent R image and played around with it.
- Created some sample R rmd markup files. Background: https://rmarkdown.rstudio.com/authoring_quick_tour.html
- Tried with knit button  to make a PDF (Knit PDF) out of them (render and output as PDF)

![R Studio Latex PDF Gen Error](https://github.com/user-attachments/assets/9eaf3929-b884-4d1f-8a9e-1fcf94051077)

**What did you expect to happen:**
@guimou Expected pdf file to be rendered and created.

**Anything else you would like to add:**
solved it by installing in the base OS CentOS 9 the following package (in Containerfile / Dockerfile):
From CentOS 9 appstream repo.

`RUN yum install -y texlive-framed`

After that, the PDF from markup, with Knit on the R Studio UI, was rendered and created correctly in a new popup window, frame, I guess.

Got the hint from 

https://github.com/rstudio/rmarkdown/issues/39

**Environment:**

- OpenDatahub Version: (please check the operator version)
- Workbench: (all, data-science, etc)
- Workbench Version: (2023.1, etc)
- Specific tool: (jupyterlab, rstudio server, code-server, elyra-pipelines,etc)
- Notebook-Controller Version: (please check the image version in notebook-controller deployment)

**Logs/Screenshots**

**Comment by jiridanek** [comment]
This is broken in JupyterLab as well,

* https://github.com/opendatahub-io/notebooks/issues/210
* https://github.com/opendatahub-io-contrib/workbench-images/pull/37/files

**Comment by shalberd** [comment]
> This is broken in JupyterLab as well

interesting, requires e.g. different OS packages, compared to what I list / install here for R Studio. Thank you for the cross-linking here, cool
