### ISSUE TITLE
Include CUDA toolkit on the CentOS base image

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io/notebooks#95]
Include CUDA toolkit on the CentOS base image

**Comment by guimou** [comment]
The CUDA toolkit is necessary to install some Python packages as even the pip install relies on nvcc being available (e.g. flash-attn, used with LLM, does not distribute wheels but source only, and therefore must be compiled with nvcc for installation).
And you need CentOS Stream for the CUDA Toolkit to install...
Seems like most if not all CUDA images should use CentOS Stream...
