### ISSUE TITLE
PyTorch should be installed from Torch repo, not from PyPi

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/notebooks#98]
As PyTorch comes with its own embedded CUDA, we have to make sure we match the CUDA version (and Toolkit) we install in the image with the one from PyTorch. The only way to that is to install from the original PyTorch repo: https://download.pytorch.org/whl/torch_stable.html
We can then specify the exact version we want, like torch==1.9.0+cu111, which would install Torch with CUDA11.1.

**Comment by harshad16** [comment]
The work was completed in sprint 1.29
The PR is kept in waiting state, as it update the pytorch version with major change
which is to be updated in 2023b cycle.
This issue would be staled till that period.

keeping the issue in 1.29 for now
it would be moved to appropriate sprint as august starts.

**Comment by harshad16** [comment]
Complete with #205
Thanks for the work.
